<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxF38mm\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxF38mm/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSxF38mm.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSxF38mm\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSxF38mm\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'SxF38mm',
    'container.build_id' => 'ca787efa',
    'container.build_time' => 1540203593,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxF38mm');
