<?php

namespace App\Presenters;

use Nette;
use Nextras\Application\UI\SecuredLinksPresenterTrait;


abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    use SecuredLinksPresenterTrait;

    /**
     * @param $element
     * @throws Nette\Application\AbortException
     * @throws Nette\Application\ForbiddenRequestException
     */
    public function checkRequirements($element): void
    {
        parent::checkRequirements($element); // TODO: Change the autogenerated stub
        if (!$this->user->isAllowed($this->getName(), $this->getAction())) {
            $this->noPermissionRedirect();
        }
    }

    /**
     * @throws Nette\Application\AbortException
     */
    protected function startup(): void
    {
        parent::startup();
//
//        if (!$this->user->isAllowed($this->getName(), $this->getAction())) {
//            $this->noPermissionRedirect();
//        }
    }

    /**
     * @throws Nette\Application\AbortException
     */
    protected function noPermissionRedirect(): void
    {
        $this->flashMessage('No permission', 'alert-danger');
        $this->redirect('Homepage:');
    }

    /**
     * @return bool
     */
    protected function isUserAdmin(): bool
    {
        return $this->user->isInRole('admin');
    }
}
